### ISSUE TITLE
Fix: Plan lesson creates None type error

### ISSUE THREAD

**Issue by drussell1974** [drussell1974/cssow#757]
https://teach.rujl.net/profile/5/schemesofwork/206/lessons/463/schedules/34/lesson-plan

TypeError at /profile/5/schemesofwork/206/lessons/463/schedules/34/lesson-plan
'>' not supported between instances of 'NoneType' and 'int'

**Comment by drussell1974** [comment]
Environment:


Request Method: GET
Request URL: https://teach.rujl.net/profile/5/schemesofwork/206/lessons/463/schedules/34/lesson-plan

Django Version: 4.2.3
Python Version: 3.10.5
Installed Applications:
['shared.models',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'debug_toolbar',
 'corsheaders']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'corsheaders.middleware.CorsMiddleware']



Traceback (most recent call last):
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/decorators/permissions.py", line 71, in inner
    return func(auth_ctx=auth_ctx, *args, **kwargs)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/app/lesson_schedules/views.py", line 214, in ai_lesson_plan
    viewmodel = LessonScheduleLessonPlanAIModelViewModel(db=db, request=request, schedule_id=schedule_id, lesson_id=lesson_id, scheme_of_work_id=scheme_of_work_id, auth_user=auth_ctx)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/app/lesson_schedules/viewmodels.py", line 342, in __init__
    elif self.lesson_model.lesson_plan_id > 0:

Exception Type: TypeError at /profile/5/schemesofwork/206/lessons/463/schedules/34/lesson-plan
Exception Value: '>' not supported between instances of 'NoneType' and 'int'
