### ISSUE TITLE
Fix: Error editing lesson

### ISSUE THREAD

**Issue by drussell1974** [drussell1974/cssow#758]
https://teach.rujl.net/profile/5/schemesofwork/206/lessons/467/edit

**Comment by drussell1974** [comment]
Environment:


Request Method: GET
Request URL: https://teach.rujl.net/profile/5/schemesofwork/206/lessons/467/edit

Django Version: 4.2.3
Python Version: 3.10.5
Installed Applications:
['shared.models',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'debug_toolbar',
 'corsheaders']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'corsheaders.middleware.CorsMiddleware']



Traceback (most recent call last):
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/db/backends/utils.py", line 61, in callproc
    return self.cursor.callproc(procname, params)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/cursors.py", line 322, in callproc
    self._query(q)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)

The above exception ((1305, 'PROCEDURE drussell1974$cssow_api.topic__get_lesson_options does not exist')) was the direct cause of the following exception:
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/core/db_helper.py", line 140, in select
    raise e
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/core/db_helper.py", line 119, in select
    self.cur.callproc(sql, params)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/db/backends/utils.py", line 57, in callproc
    with self.db.wrap_database_errors:
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/db/backends/utils.py", line 61, in callproc
    return self.cursor.callproc(procname, params)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/cursors.py", line 322, in callproc
    self._query(q)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)

During handling of the above exception ((1305, 'PROCEDURE drussell1974$cssow_api.topic__get_lesson_options does not exist')), another exception occurred:
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/decorators/permissions.py", line 71, in inner
    return func(auth_ctx=auth_ctx, *args, **kwargs)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/app/lessons/views.py", line 155, in edit
    topic_options = TopicModel.get_lesson_options(db, auth_ctx=auth_ctx)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/cls_topic.py", line 157, in get_lesson_options
    rows = TopicDataAccess.get_lesson_options(db, institute_id=auth_ctx.institute_id, scheme_of_work_id=auth_ctx.scheme_of_work_id, auth_user_id=auth_ctx.auth_user_id, show_published_state=STATE.PUBLISH)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/cls_topic.py", line 311, in get_lesson_options
    rows = execHelper.select(db, str_select, params, rows, handle_log_info)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/decorators/profiler.py", line 65, in inner
    res = func(*args, **kwargs)
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/core/db_helper.py", line 142, in select
    self.end()
  File "/home/drussell1974/sites/cssow_api/teacher-web/web/shared/models/core/db_helper.py", line 76, in end
    self.cur.close()
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/cursors.py", line 103, in close
    self._discard()
  File "/home/drussell1974/.virtualenvs/django_python3_10/lib/python3.10/site-packages/MySQLdb/cursors.py", line 95, in _discard
    while con.next_result() == 0:  # -1 means no more data.

Exception Type: OperationalError at /profile/5/schemesofwork/206/lessons/467/edit
Exception Value: (2006, '')

**Comment by drussell1974** [comment]
Create topic__get_lesson_options
