### ISSUE TITLE
Fix: jest fails due to invalid document in domManipulator as part of verifying git commits

### ISSUE THREAD

**Issue by drussell1974** [drussell1974/cssow#788]
during commit
```
 ReferenceError: document is not defined

       5 | export const createContainer = () => {
       6 |     
    >  7 |     const container = document.createElement('div');
         |                       ^
       8 |     
       9 |     const form = id => container.querySelector(`form[id="${id}"]`);
      10 |     

      at document (helpers/domManipulators.js:7:23)
      at Object.<anonymous> (__tests__/NotificationWidget.test.js:11:47)
```

**Comment by drussell1974** [comment]
Must run in virtualenv. Node version conflict requires resolution
